### ISSUE TITLE
Issue with input: IPAPath parameter must be specifed when DSYMPath is missing

### ISSUE THREAD

**Issue by Rusttom** [bitrise-io/steps-hockeyapp-deploy#26] opened 2017-08-10 10:13 UTC
+------------------------------------------------------------------------------+

| (8) hockeyapp-deploy                                                         |
+------------------------------------------------------------------------------+
| id: hockeyapp-deploy                                                         |
| version: 2.4.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-08-10T02:25:57-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[02:25:57]  * [OK] Step dependency (go) installed, available. 
Configs:
- IPAPath: 
- DSYMPath: 
- APIToken: a1e6bde50d88484f8a1758c5177d55fc
- AppID: 7933bdfcb19c467eb5d1ebd951f05de3
- Notes: Deploy with Bitrise HockeyApp Deploy Step.
- NotesType: 0
- Notify: 2
- Status: 2
- Mandatory: false
- Tags: 
- CommitSHA: 
- BuildServerURL: https://www.bitrise.io/build/48fa435a188203dc
- RepositoryURL: 
Issue with input: IPAPath parameter must be specifed when DSYMPath is missing
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | hockeyapp-deploy (exit code: 1)                               | 4.75 sec |

https://www.screencast.com/t/zaycda3c

Why - IPAPath: and DSYMPath: are empty?

**Comment by viktorbenei** [comment] 2017-08-10 10:32
Closing as duplicate of: https://discuss.bitrise.io/t/build-error-missing-ipa-file-when-building-to-hockey-app/1186

**Closed by viktorbenei** 2017-08-10 10:32 UTC
